name: outdoor_aerial_client
description: "永远热爱户外和广播"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  another_flutter_splash_screen: ^1.2.1
  dynamic_color: ^1.8.1
  flutter_local_notifications: ^19.5.0
  flutter_tabler_icons: ^1.43.0
  flutter_riverpod: ^3.0.3
  flutter_soloud: ^3.4.8
  go_router: ^17.0.1
  isar_community: ^3.3.0
  isar_community_flutter_libs: ^3.3.0
  path_provider: ^2.1.5
  protobuf: ^6.0.0
  riverpod_annotation: ^3.0.3
  web_socket_channel: ^3.0.3
  audio_service: ^0.18.18
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: any
  custom_lint: any
  isar_community_generator: ^3.3.0
  riverpod_generator: ^3.0.3
  riverpod_lint: ^3.0.3

flutter:
  uses-material-design: true
  generate: true
  fonts:
    - family: AlibabaPuHuiTi
      fonts:
        - asset: fonts/AlibabaPuHuiTi-Regular.ttf
