name: outdoor_aerial_client
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  audio_service: ^0.18.18
  another_flutter_splash_screen: ^1.2.1
  dynamic_color: ^1.8.1
  flutter_tabler_icons: ^1.43.0
  flutter_riverpod: ^3.0.3
  flutter_soloud: ^3.2.2
  flutter_staggered_grid_view: ^0.7.0
  go_router: ^16.1.0
  m3e_collection: ^0.3.7
  protobuf: ^6.0.0
  riverpod_annotation: ^3.0.3
  web_socket: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  riverpod_generator: ^3.0.3
  custom_lint: ^0.8.1
  riverpod_lint: ^3.0.3
  build_runner: ^2.10.4

flutter:
  uses-material-design: true
  generate: true
  fonts:
    - family: AlibabaPuHuiTi
      fonts:
        - asset: fonts/AlibabaPuHuiTi-Regular.ttf
  assets:
    - assets/